"""Symmetric encryption for per-user connection secrets (Fernet).

The master key comes from the ``CONNECTIONS_SECRET_KEY`` env var (a url-safe
base64 32-byte Fernet key, generated by the installer). Without it the feature
is disabled and secrets are never stored in plaintext.
"""
from __future__ import annotations

import os

from cryptography.fernet import Fernet, InvalidToken

_ENV_VAR = "CONNECTIONS_SECRET_KEY"


class ConnectionsDisabledError(RuntimeError):
    """Raised when a secret operation is attempted without CONNECTIONS_SECRET_KEY."""


class SecretDecryptError(RuntimeError):
    """Raised when ciphertext can't be decrypted (wrong/rotated key or corruption)."""


def is_enabled() -> bool:
    """True if the master key is configured."""
    return bool(os.environ.get(_ENV_VAR, "").strip())


class SecretBox:
    """Encrypt/decrypt helper bound to the configured master key."""

    def __init__(self, key: str):
        self._fernet = Fernet(key.encode())

    @classmethod
    def from_env(cls) -> "SecretBox":
        key = os.environ.get(_ENV_VAR, "").strip()
        if not key:
            raise ConnectionsDisabledError(
                f"{_ENV_VAR} is not set — connections feature is disabled"
            )
        return cls(key)

    def encrypt(self, plaintext: str) -> str:
        return self._fernet.encrypt(plaintext.encode()).decode()

    def decrypt(self, token: str) -> str:
        try:
            return self._fernet.decrypt(token.encode()).decode()
        except (InvalidToken, ValueError) as exc:
            raise SecretDecryptError("cannot decrypt secret") from exc
