"""Symmetric encryption for per-user Anthropic API keys (Fernet).

Thin wrapper around :class:`cryptography.fernet.Fernet`. Unlike the connections
``SecretBox``, :meth:`ApiKeyCrypto.decrypt` returns ``None`` on any failure
(wrong/rotated key, corruption, malformed input) so callers can degrade
gracefully instead of catching exceptions.

The ``secret`` is a url-safe base64-encoded 32-byte Fernet key (the same format
generated by ``Fernet.generate_key()`` and by the installer).
"""
from __future__ import annotations

from cryptography.fernet import Fernet, InvalidToken


class ApiKeyCrypto:
    """Encrypt and decrypt API keys with a Fernet cipher."""

    def __init__(self, secret: str):
        self._fernet = Fernet(secret.encode())

    def encrypt(self, key: str) -> str:
        """Return the Fernet token (url-safe base64 text) for ``key``."""
        return self._fernet.encrypt(key.encode()).decode()

    def decrypt(self, encrypted: str) -> str | None:
        """Return the plaintext key, or ``None`` if it cannot be decrypted."""
        try:
            return self._fernet.decrypt(encrypted.encode()).decode()
        except (InvalidToken, ValueError, TypeError):
            return None
